{% set name = "csl" %}
{% set version = "1.6.0" %}

package:
  name: rb-{{ name|lower }}
  version: {{ version }}

source:
  url: https://rubygems.org/downloads/{{ name }}-{{ version }}.gem
  sha256: 33332fab7d2d11ba3cf2481833eafbe3938e84f48791ec7858c2e3bd7fc51159

build:
  noarch: generic
  number: 0
  script:
    - gem install -N -l -V --norc --ignore-dependencies {{ name }}-{{ version }}.gem
    - gem unpack {{ name }}-{{ version }}.gem
  skip: {{ win }}

requirements:
  host:
    - ruby
  run:
    - ruby
    - rb-namae >=1.0,<2

test:
  commands:
    - ruby -r {{ name }} -e 'exit 0'

about:
  home: https://rubygems.org/gems/{{ name }}
  license: BSD-2-Clause
  license_family: BSD
  license_file: {{ name }}-{{ version }}/BSDL
  summary: A Ruby parser and full API for the Citation Style Language (CSL).

  # The remaining entries in this section are optional, but recommended.
  doc_url: https://www.rubydoc.info/gems/{{ name }}
  dev_url: https://github.com/inukshuk/{{ name }}

extra:
  recipe-maintainers:
    - sodre
