travis:
  secure:
    BINSTAR_TOKEN: uU6m26W0Y80uGiRiBz28IcmSZJk3yJqWihaqrRwQ535Mx7f6FwDvVQsRtkh4/vgH8V23lS4nqlmd+LTUC1d2ZejoklxyAwucAutWjfrTT7O8kMZjXO6UDBTEkqk6TJpxErXu91kOMyQKN4X/D3l5A1yvniA1fU1OBv0XexFYUHi6XFOr4QNNnY2WXsySYX5DYBM/kHR6JP7sMNTUJh8OubgPyG0ajAd9dBr5Y16+RcMWetDCslmVNAno+fjVyH1kGkH6bYWt7qvHkkztFIH3q2Wx5mYlxiUUTn8IdKk6smgbZPgOBE8DZiO/bP908wz0ihICuHwYIJ6rysms23xgeNS34wfRkJ46frsZht4K0mgLgMmV7l9qWPl7bWmVfMSufS/PN/we2ELKWl5ev0669jc1SQfUei11aMcRdkFZN4JQYlDY+g/CS5YlvOGUTSo6PmUgniojbpyqRxcZZz63jkh8a19Fx8y/mFADSdUeHlVPjpkN23Qj4kYqeC5kYvPQ46Ihhko5YdD42X3eTYBhE5R5xACItFXi7j1BlR2qNbw6smJLAJ5Ap+CmHcdS5HKOAMiV0PpRGIsUaXInpXexSSec7uHllR7n3yY/sjn0QMqmloGqMvR1c722T7r7byo1BYN4PArA2bq4tfI6+cVi9rgLMAUrg/8ArYurpCh+RX8=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
